version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - chmod 777 gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes 